name: auto_readme
on:
  workflow_dispatch:
    inputs:
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean 
  push:
    paths:
      - 'do_think/**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create_readme
        run: ./create_readme.sh
      - name: commit readme
        run: |
          git config --global user.name 'ccagml'
          git config --global user.email 'ccagml@163.com'
          git commit -am "auto readme"
          git push